apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: nginx:latest
    livenessProbe: #determina si el pod esta vivo o sano
      exec:
        command:
        - curl
        - localhost
      initialDelaySeconds: 20 #espera n segundos para empezar a realizar el chequeo
      periodSeconds: 5 # realiza el chequeo cada n segundos
